version: "3"

services:
  wordpress:
    container_name: wp-citwatch
    image: wordpress
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./wp-content:/var/www/html/wp-content

  gulp:
    platform: linux/x86_64
    build:
      dockerfile: Dockerfile-gulp
      context: .
    command: gulp default
    ports:
      - '8002:8002'
    volumes:
      - ${GULP_THEME_DIR}:/bundle  # Use the variable here

  # Services for local database:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 80M
    ports:
      - 8881:80
